version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8

  pre_build:
    commands:
      - echo "Fetching CodeArtifact token..."
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain nextwork --repository nextwork-devops-cicd --domain-owner 242201292097 --region eu-west-1 --query authorizationToken --output text)
      - echo "Token acquired"

  build:
    commands:
      - mvn -B -e clean compile -s settings.xml
      - mvn -B -e package -s settings.xml

artifacts:
  files:
    - target/*.war
    - appspec.yml
    - scripts/**/*
  discard-paths: no